### ISSUE TITLE
Thesis information

### ISSUE THREAD

**Issue by samayala22** [Xinrui/CorotationalBeamSolver#2]
Not a software issue per say, but where can I find your thesis related to this project ? If I'm correct, the title is:

"Investigation and Improvement of a Co-Rotational 3D Beam Element Including Plasticity and Non- Linear Local Element Formulation"

This would help understand the plasticity implementation and control strategies. 

Also, does this solver work with moment loads (for a cantilever tip moment test case) ? I tried with a simple function analogous to how `add_load` works but setting the last 3 load components instead of the first 3 but the solver rapidly diverges.

**Comment by xinrui** [comment]
Hi,

Could you give me your email address here? So I can send a copy of my thesis.

I've never tried mutiple loads (all my cases are loaded singly) and moments, so i am very sure that there are bugs in my program :( 

I would suggest referring to the bibliography, some of which are quite inspiring, and using a programming language with static type.

**Comment by samayala22** [comment]
There you go: freresayala22@gmail.com

**Comment by zerongit** [comment]
Hi there, sorry for commenting on this closed issue. I'm also very interested in this project and the related thesis. Could you please send me a copy of the thesis as well? 
Here's my email: mzl012123@gmail.com
